from __future__ import annotations

import base64
import logging

import httpx
from fastapi import APIRouter, Depends, UploadFile, File, Query
from pydantic import BaseModel

from app.config import settings
from app.middleware.auth import verify_internal_token

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/imaging", tags=["imaging"])


class ImagingAnalysisResponse(BaseModel):
    findings: list[str]
    impression: str
    severity: str | None
    follow_up_recommended: bool
    model_used: str


async def _call_vertex_endpoint(endpoint_id: str, image_bytes: bytes, mime_type: str) -> dict:
    """
    Call a Vertex AI custom endpoint (CXR Foundation / MedSigLIP).
    Sends image as base64-encoded inline data.
    """
    import google.auth
    import google.auth.transport.requests

    credentials, _ = google.auth.default(
        scopes=["https://www.googleapis.com/auth/cloud-platform"]
    )
    credentials.refresh(google.auth.transport.requests.Request())

    url = (
        f"https://{settings.vertex_ai_location}-aiplatform.googleapis.com/v1/"
        f"projects/{settings.google_cloud_project_id}/locations/{settings.vertex_ai_location}/"
        f"endpoints/{endpoint_id}:predict"
    )

    payload = {
        "instances": [
            {
                "content": base64.b64encode(image_bytes).decode("utf-8"),
                "mimeType": mime_type,
            }
        ]
    }

    async with httpx.AsyncClient(timeout=60.0) as client:
        resp = await client.post(
            url,
            json=payload,
            headers={"Authorization": f"Bearer {credentials.token}"},  # type: ignore[attr-defined]
        )
        resp.raise_for_status()
        return resp.json()


def _parse_cxr_response(raw: dict) -> ImagingAnalysisResponse:
    predictions = raw.get("predictions", [{}])[0]
    findings = predictions.get("findings", [])
    impression = predictions.get("impression", "Preliminary report generated by CXR Foundation model.")
    severity = predictions.get("severity")
    follow_up = predictions.get("follow_up_recommended", False)
    return ImagingAnalysisResponse(
        findings=findings if isinstance(findings, list) else [str(findings)],
        impression=impression,
        severity=severity,
        follow_up_recommended=follow_up,
        model_used="cxr-foundation",
    )


def _parse_medsiglip_response(raw: dict, image_type: str) -> ImagingAnalysisResponse:
    predictions = raw.get("predictions", [{}])[0]
    findings = predictions.get("findings", [])
    impression = predictions.get("impression", f"Preliminary {image_type} analysis by MedSigLIP.")
    severity = predictions.get("severity")
    follow_up = predictions.get("follow_up_recommended", False)
    return ImagingAnalysisResponse(
        findings=findings if isinstance(findings, list) else [str(findings)],
        impression=impression,
        severity=severity,
        follow_up_recommended=follow_up,
        model_used="medsiglip",
    )


@router.post("/cxr", response_model=ImagingAnalysisResponse, dependencies=[Depends(verify_internal_token)])
async def analyze_chest_xray(image: UploadFile = File(...)) -> ImagingAnalysisResponse:
    """
    Chest X-ray analysis using CXR Foundation model on Vertex AI.
    Mode: Async job (< 30s latency budget).
    """
    if not settings.cxr_model_endpoint:
        raise ValueError("CXR_MODEL_ENDPOINT not configured")

    image_bytes = await image.read()
    mime_type = image.content_type or "image/jpeg"

    raw = await _call_vertex_endpoint(settings.cxr_model_endpoint, image_bytes, mime_type)
    return _parse_cxr_response(raw)


@router.post("/analyze", response_model=ImagingAnalysisResponse, dependencies=[Depends(verify_internal_token)])
async def analyze_image(
    image: UploadFile = File(...),
    image_type: str = Query(default="dermatology"),
) -> ImagingAnalysisResponse:
    """
    General medical image analysis (dermatology, wound) using MedSigLIP.
    Mode: Async job (< 30s latency budget).
    """
    if not settings.cxr_model_endpoint:
        raise ValueError("MedSigLIP endpoint not configured")

    image_bytes = await image.read()
    mime_type = image.content_type or "image/jpeg"

    raw = await _call_vertex_endpoint(settings.cxr_model_endpoint, image_bytes, mime_type)
    return _parse_medsiglip_response(raw, image_type)
